---
ruler_x: 316
ruler_y: 382
ruler_length: 648
track_mouse: false
metric: 0
keep_above: false
foreground_color: "#202020"
background_color: "#e6e36b"
font: Sans 12
opacity: 0.85
use_custom_pixels_per_inch: false
horizontal_pixels_per_inch: 96.18934911242604
vertical_pixels_per_inch: 96.18934911242604
