#! /bin/sh

bspc config border_width        2
bspc config focused_border_color	\#57503a
bspc config window_gap         5 
bspc config top_padding	       26	

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Firefox desktop=^1 follow=on
bspc rule -a Emacs desktop=^3
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ij-ImageJ state=floating
#bspc rule -a fiji-Main desktop=^5 floating=on

/home/noah/.config/bar/bar-fork2.sh &
compton --config /home/noah/.config/compton.conf &
xkbcomp -I$HOME/.xkb ~/.xkb/keymap/mykbd $DISPLAY &
xrdb -merge ~/.Xresources &
urxvtd &
#feh --bg-tile /home/noah/Desktop/pink.jpg & 
nitrogen --restore &
wmname LG3D
